name: Node CI and Deploy to Docker & Packages

on:
  push:
    branches: [main]

jobs:
  test:
    name: Testing code before deployment
    runs-on: ubuntu-latest
    env:
      SECRET_NUMBER: ${{secrets.SECRET_NUMBER}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Clean install dependencies
        run: npm ci
      - name: Run Jest test suite
        run: npm run test
  push_to_docker:
    name: Push to Docker Image on the Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dchancellor/testing-new-docker-image:latest