name: Node CI and Deploy to Docker & Packages

on:
  push:
    branches: [main]

jobs:
  test:
    name: Testing code before deployment
    runs-on: ubuntu-latest
    env:
      SECRET_NUMBER: ${{secrets.SECRET_NUMBER}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Clean install dependencies
        run: npm ci
      - name: Run Jest test suite
        run: npm run test
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g' 